### PR TITLE
(feat): add ubuntu22 image + build process, update docs

### PR DESCRIPTION
**Pull request by traktuner**
Included in this PR:
-) new :ubuntu22 docker tag with jlesage's ubuntu22 baseimage-gui
-) updated build process
-) readme + changelog updated

The ubuntu20 image will still serve as the default image, as discussed.
The ubuntu18 and ubuntu22 images can only be used with the corresponding tags.

### CODE REVIEW

**Comment by JonathanTreffler** [comment]
Thank you for the PR :)

**Review by JonathanTreffler — CHANGES_REQUESTED** [review]
The Build Action for the ubuntu 22 action currently fails for this PR, because it tries to push to the tag :pr-85:ubuntu22. Please disabled PR image tags for the ubuntu 22 image, so it behaves like ubuntu18, which just builds the image in PRs, but doesn't try to push it.

**Comment by traktuner** [comment]
Also fixes #71
Bildschirmfoto 2023-12-12 um 16 00 30

**Review by JonathanTreffler — APPROVED** [review]
:+1:

**Pull request merged**
