### PR TITLE
(feat): new known-good bz version 9.0.1.763 + update docs

### PR DESCRIPTION
**Pull request by traktuner**
In this PR:
-) update known-good version to 9.0.1.763
-) added a "black screen" troubleshooting section to readme
-) update version to 1.6.1, please adapt or remove it as you like :)

### CODE REVIEW

**Comment by traktuner** [comment]
supersedes #101

**Review by JonathanTreffler — APPROVED** [review]

**Comment by traktuner** [comment]
@JonathanTreffler could you please test this on your setup if the auto update works for you?
For me it went well, updater started as expected when starting the container. One click on install and it started backing up again.

**Comment by JonathanTreffler** [comment]
> @JonathanTreffler could you please test this on your setup if the auto update works for you? For me it went well, updater started as expected when starting the container. One click on install and it started backing up again. (Because this would be the first time that everybody gets the auto-updater at start)

(I don't have a personal setup, but I can just create one for the test, but I don't know, when I will have time.)

**Comment by traktuner** [comment]
> > @JonathanTreffler could you please test this on your setup if the auto update works for you? For me it went well, updater started as expected when starting the container. One click on install and it started backing up again. (Because this would be the first time that everybody gets the auto-updater at start)
> 
> (I don't have a personal setup, but I can just create one for the test, but I don't know when I will have time.)

All good ;) I tested it numerous times now, the installer appears every time, the download from archive.org is sometimes very fast and sometimes really slow, so it may take a while for the updater to appear.
I will add that to the changelog as an information and would merge it after that.

**Pull request merged**
